### ISSUE TITLE
Просто хочу сказать огромное спасибо за прогу

### ISSUE THREAD

**Issue by Vponed** [trufanov-nok/ex4g_dde#1]
Без простого вывода данных по ДДЕ у меня вся работа стояла, теперь наконец-то могу программно обрабатывать данные из квика. На луа даже смотреть не хотел, самому поднять дде-сервер не получалось, ексел ставить тоже не хотелось. Долго искал, и вот нашел. Счастья вам, здоровья и творческих успехов 
ЗЫ. Мегабайт! Она занимает всего один мегабайт памяти! А сколько пользы...

**Comment by trufanov-nok** [comment]
Добрый день! Спасибо, но это не моя программа - я к ней не имею отношения. Её насписал roboex, который доступен по email roboex@mail.ru  и web-сайту http://roboex.narod.ru   

Более того у него на сайте есть версия программы поновее, но, к сожалению, без исходников.    

Я когда-то искал возможности экспорта тиковых данных из QUIK в другие программы и скопировал его проект, рассчитывая что в дальнейшем буду изменять код под свои задачи. Но в итоге DDE мне так и не подошел - мне нужно было обеспечить высокоскоростную передачу данных из запущенного через Wine QUIK'а в программу на Linux. Я предпочел сделать экспорт данных через Lua плагин, подтягивающий мою DLL'ку, которая просто пишет все что получает в stdout программы: https://github.com/trufanov-nok/quik_lua_export

**Comment by Vponed** [comment]
Переправил ему благодарность.
Ваш код тоже скачал, благодарю.
Он пишет вообще все, или можно как-то задать выборку?

**Comment by trufanov-nok** [comment]
Если я правильно помню, dll'ка пишет в stdout некоторый набор полей таблицы OnAllTrade без фильтрации. Эта таблица должна быть открыта в QUIK, и фильтры, например по интересующим ticker'ам, для нее задаются тоже в QUIK.  Т.о. фильтрация на стороне интерфейса QUIKа.

**Comment by Vponed** [comment]
> Если я правильно помню, dll'ка пишет в stdout некоторый набор полей таблицы OnAllTrade без фильтрации. Эта таблица должна быть открыта в QUIK, и фильтры, например по интересующим ticker'ам, для нее задаются тоже в QUIK. Т.о. фильтрация на стороне интерфейса QUIKа.

Кажется понял. Вот это место: "return quik_lua_export.OnAllTrade(alltrades)"
alltrades я так понимаю, это имя таблицы
А если надо вывести несколько?

**Comment by trufanov-nok** [comment]
alltrades - имя аргумента функции. Посмотрел в API: всего в QUIK [примерно 20 таблиц](http://luaq.ru/getItem.html#param_table_23) и почти столько же [функций обратного вызова](http://luaq.ru/OnAllTrade.html) для них. Мой пример демонстрирует вывод всех поступающих обезличенных сделок из таблицы all_trades. При попадании в нее данных QUIK вызывает функцию OnAllTrade, которая передает ее в C++, и оттуда все печатается в stdout, т.к. сам Lua печатать в stdout не умеет. Если вас интересуют другие данные, например данные таблицы Сделок trades, то в Lua нужно объявить функцию 
```
function OnTrade(trades)
    return quik_lua_export.OnTrade(trades)
end
```
А в C++ писать обработчик для OnTrade.

**Comment by Vponed** [comment]
> alltrades - имя аргумента функции. Посмотрел в API: всего в QUIK [примерно 20 таблиц](http://luaq.ru/getItem.html#param_table_23) и почти столько же [функций обратного вызова](http://luaq.ru/OnAllTrade.html) для них. Мой пример демонстрирует вывод всех поступающих обезличенных сделок из таблицы all_trades. При попадании в нее данных QUIK вызывает функцию OnAllTrade, которая передает ее в C++, и оттуда все печатается в stdout, т.к. сам Lua печатать в stdout не умеет. Если вас интересуют другие данные, например данные таблицы Сделок trades, то в Lua нужно объявить функцию
> 
> ```
> function OnTrade(trades)
>     return quik_lua_export.OnTrade(trades)
> end
> ```
> 
> А в C++ писать обработчик для OnTrade.

Понял вас, большое спасибо, сохраню на память
